//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.4.0-b180830.0438 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.12.10 at 08:21:34 PM IST 
//

package com.searshc.nfx624.nfx624;

import java.io.Serializable;

public class B1TransactionHeaderRecordSegment implements Serializable {

	private final static long serialVersionUID = 1L;
	protected String indicator;
	protected Short segmentLength;
	protected String storeNumber;
	protected String registerNumber;
	protected String transactionNumber;
	protected String transactionDate;
	protected String transactionTime;
	protected String creditedStoreNumber;
	protected String ringingAssociateNumber;
	protected String purchasingCustomerID;
	protected String purchasingAddressID;
	protected String customerIDStatusCode;
	protected String transactionSourceCode;
	protected String transactionTypeCode;
	protected String transactionStatusCode;
	protected String transactionErrorCode;
	protected String transactionReasonCode;
	protected String transactionTotalDiscount;
	protected String transactionTotalDiscountSIN;
	protected String transactionTotalTax;
	protected String transactionTotalTaxSIN;
	protected String transactionTaxCode;
	protected String transactionTotal;
	protected String transactionTotalSIN;
	protected String transactionFlags;

	/**
	 * Gets the value of the indicator property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getIndicator() {
		return indicator;
	}

	/**
	 * Sets the value of the indicator property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setIndicator(String value) {
		this.indicator = value;
	}

	/**
	 * Gets the value of the segmentLength property.
	 * 
	 * @return possible object is {@link Short }
	 * 
	 */
	public Short getSegmentLength() {
		return segmentLength;
	}

	/**
	 * Sets the value of the segmentLength property.
	 * 
	 * @param value allowed object is {@link Short }
	 * 
	 */
	public void setSegmentLength(Short value) {
		this.segmentLength = value;
	}

	/**
	 * Gets the value of the storeNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getStoreNumber() {
		return storeNumber;
	}

	/**
	 * Sets the value of the storeNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setStoreNumber(String value) {
		this.storeNumber = value;
	}

	/**
	 * Gets the value of the registerNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRegisterNumber() {
		return registerNumber;
	}

	/**
	 * Sets the value of the registerNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setRegisterNumber(String value) {
		this.registerNumber = value;
	}

	/**
	 * Gets the value of the transactionNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionNumber() {
		return transactionNumber;
	}

	/**
	 * Sets the value of the transactionNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionNumber(String value) {
		this.transactionNumber = value;
	}

	/**
	 * Gets the value of the transactionDate property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionDate() {
		return transactionDate;
	}

	/**
	 * Sets the value of the transactionDate property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionDate(String value) {
		this.transactionDate = value;
	}

	/**
	 * Gets the value of the transactionTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTime() {
		return transactionTime;
	}

	/**
	 * Sets the value of the transactionTime property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTime(String value) {
		this.transactionTime = value;
	}

	/**
	 * Gets the value of the creditedStoreNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCreditedStoreNumber() {
		return creditedStoreNumber;
	}

	/**
	 * Sets the value of the creditedStoreNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCreditedStoreNumber(String value) {
		this.creditedStoreNumber = value;
	}

	/**
	 * Gets the value of the ringingAssociateNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getRingingAssociateNumber() {
		return ringingAssociateNumber;
	}

	/**
	 * Sets the value of the ringingAssociateNumber property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setRingingAssociateNumber(String value) {
		this.ringingAssociateNumber = value;
	}

	/**
	 * Gets the value of the purchasingCustomerID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPurchasingCustomerID() {
		return purchasingCustomerID;
	}

	/**
	 * Sets the value of the purchasingCustomerID property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPurchasingCustomerID(String value) {
		this.purchasingCustomerID = value;
	}

	/**
	 * Gets the value of the purchasingAddressID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPurchasingAddressID() {
		return purchasingAddressID;
	}

	/**
	 * Sets the value of the purchasingAddressID property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setPurchasingAddressID(String value) {
		this.purchasingAddressID = value;
	}

	/**
	 * Gets the value of the customerIDStatusCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCustomerIDStatusCode() {
		return customerIDStatusCode;
	}

	/**
	 * Sets the value of the customerIDStatusCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setCustomerIDStatusCode(String value) {
		this.customerIDStatusCode = value;
	}

	/**
	 * Gets the value of the transactionSourceCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionSourceCode() {
		return transactionSourceCode;
	}

	/**
	 * Sets the value of the transactionSourceCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionSourceCode(String value) {
		this.transactionSourceCode = value;
	}

	/**
	 * Gets the value of the transactionTypeCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTypeCode() {
		return transactionTypeCode;
	}

	/**
	 * Sets the value of the transactionTypeCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTypeCode(String value) {
		this.transactionTypeCode = value;
	}

	/**
	 * Gets the value of the transactionStatusCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionStatusCode() {
		return transactionStatusCode;
	}

	/**
	 * Sets the value of the transactionStatusCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionStatusCode(String value) {
		this.transactionStatusCode = value;
	}

	/**
	 * Gets the value of the transactionErrorCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionErrorCode() {
		return transactionErrorCode;
	}

	/**
	 * Sets the value of the transactionErrorCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionErrorCode(String value) {
		this.transactionErrorCode = value;
	}

	/**
	 * Gets the value of the transactionReasonCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionReasonCode() {
		return transactionReasonCode;
	}

	/**
	 * Sets the value of the transactionReasonCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionReasonCode(String value) {
		this.transactionReasonCode = value;
	}

	/**
	 * Gets the value of the transactionTotalDiscount property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTotalDiscount() {
		return transactionTotalDiscount;
	}

	/**
	 * Sets the value of the transactionTotalDiscount property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTotalDiscount(String value) {
		this.transactionTotalDiscount = value;
	}

	/**
	 * Gets the value of the transactionTotalDiscountSIN property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTotalDiscountSIN() {
		return transactionTotalDiscountSIN;
	}

	/**
	 * Sets the value of the transactionTotalDiscountSIN property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTotalDiscountSIN(String value) {
		this.transactionTotalDiscountSIN = value;
	}

	/**
	 * Gets the value of the transactionTotalTax property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTotalTax() {
		return transactionTotalTax;
	}

	/**
	 * Sets the value of the transactionTotalTax property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTotalTax(String value) {
		this.transactionTotalTax = value;
	}

	/**
	 * Gets the value of the transactionTotalTaxSIN property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTotalTaxSIN() {
		return transactionTotalTaxSIN;
	}

	/**
	 * Sets the value of the transactionTotalTaxSIN property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTotalTaxSIN(String value) {
		this.transactionTotalTaxSIN = value;
	}

	/**
	 * Gets the value of the transactionTaxCode property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTaxCode() {
		return transactionTaxCode;
	}

	/**
	 * Sets the value of the transactionTaxCode property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTaxCode(String value) {
		this.transactionTaxCode = value;
	}

	/**
	 * Gets the value of the transactionTotal property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTotal() {
		return transactionTotal;
	}

	/**
	 * Sets the value of the transactionTotal property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTotal(String value) {
		this.transactionTotal = value;
	}

	/**
	 * Gets the value of the transactionTotalSIN property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionTotalSIN() {
		return transactionTotalSIN;
	}

	/**
	 * Sets the value of the transactionTotalSIN property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionTotalSIN(String value) {
		this.transactionTotalSIN = value;
	}

	/**
	 * Gets the value of the transactionFlags property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getTransactionFlags() {
		return transactionFlags;
	}

	/**
	 * Sets the value of the transactionFlags property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setTransactionFlags(String value) {
		this.transactionFlags = value;
	}

}
